import { ApiError, assertString, assertUuid, normalizeArabic, pageParams, publicExternalEligible, publicInternalEligible, safeLike } from './contracts.ts';
import { json } from './http.ts';
import { createSignedDownload, db, env } from './supabase.ts';
import { rateLimit } from './rate-limit.ts';

function ip(request:Request){return request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()??'local';}
function cache(kind:'long'|'medium'|'short'|'none'){return kind==='long'?'public, max-age=300, s-maxage=3600, stale-while-revalidate=86400':kind==='medium'?'public, max-age=30, s-maxage=300, stale-while-revalidate=900':kind==='short'?'public, max-age=0, s-maxage=3, stale-while-revalidate=5':'no-store';}
function stationStream(row:any){if(row.station_source==='EXTERNAL')return row.stream_url;const e=env();return e.streamBase?`${e.streamBase}${e.mount}`:null;}
async function publicStations(request:Request){const url=new URL(request.url);const {page,limit,from,to}=pageParams(url);const res=await db('app',`stations?deleted_at=is.null&is_active=eq.true&select=id,slug,name_ar,name_en,description,logo_url,category_id,station_source,stream_type,stream_url,timezone,status,is_featured,production_enabled,health_status,rights_status,commercial_use_status,attribution_required,attribution_text,deleted_at&order=sort_order.asc,name_ar.asc`,{headers:{range:`${from}-${to+100}`}},true);const e=env();const rows=(res.data as any[]).filter(r=>publicInternalEligible(r,e.environment)||publicExternalEligible(r)).slice(0,limit).map(r=>({id:r.id,slug:r.slug,name_ar:r.name_ar,name_en:r.name_en,description:r.description,logo_url:r.logo_url,category_id:r.category_id,station_source:r.station_source,stream_type:r.stream_type,playback_url:stationStream(r),timezone:r.timezone,status:r.status,health_status:r.health_status,is_featured:r.is_featured,attribution:r.attribution_required?r.attribution_text:null}));return json({data:rows,page,limit,total:rows.length,next_page:rows.length===limit?page+1:null},200,{'cache-control':cache('medium')});}
async function getStation(slug:string){const rows=(await db('app',`stations?slug=eq.${encodeURIComponent(slug)}&deleted_at=is.null&select=id,slug,name_ar,name_en,description,logo_url,category_id,station_source,stream_type,stream_url,timezone,status,is_featured,production_enabled,health_status,rights_status,commercial_use_status,attribution_required,attribution_text,deleted_at`)).data as any[];const r=rows[0];const e=env();if(!r||!(publicInternalEligible(r,e.environment)||publicExternalEligible(r)))throw new ApiError(404,'NOT_FOUND','Station not found');return r;}
async function publicStation(slug:string){const r=await getStation(slug);return json({data:{id:r.id,slug:r.slug,name_ar:r.name_ar,name_en:r.name_en,description:r.description,logo_url:r.logo_url,category_id:r.category_id,station_source:r.station_source,stream_type:r.stream_type,playback_url:stationStream(r),timezone:r.timezone,status:r.status,health_status:r.health_status,attribution:r.attribution_required?r.attribution_text:null}},200,{'cache-control':cache('medium')});}
async function nowPlaying(slug:string){const station=await getStation(slug);if(station.station_source!=='INTERNAL')return json({data:{station:{id:station.id,slug:station.slug},media:null,title:null,subtitle:null,started_at:null,expected_end_at:null,source:null,is_live:true,server_time:new Date().toISOString()}},200,{'cache-control':cache('short')});const rows=(await db('radio',`now_playing?station_id=eq.${station.id}&select=station_id,media_id,title,artist,started_at,expected_end_at,source_type,mode,updated_at`)).data as any[];const n=rows[0];return json({data:{station:{id:station.id,slug:station.slug,name_ar:station.name_ar,name_en:station.name_en},media:n?.media_id?{id:n.media_id}:null,title:n?.title??null,subtitle:n?.artist??null,started_at:n?.started_at??null,expected_end_at:n?.expected_end_at??null,source:n?.source_type??n?.mode??'AUTO',is_live:true,server_time:new Date().toISOString()}},200,{'cache-control':cache('short')});}
async function categories(){const data=(await db('app','categories?deleted_at=is.null&is_active=eq.true&select=id,parent_id,slug,name_ar,name_en,description,icon_key,sort_order&order=sort_order.asc,name_ar.asc')).data;return json({data},200,{'cache-control':cache('long')});}
async function reciters(request:Request){const url=new URL(request.url);const {page,limit,from,to}=pageParams(url);const q=safeLike(url.searchParams.get('q')??'');let resource=`reciters?deleted_at=is.null&is_active=eq.true&select=id,slug,name_ar,name_en,image_url,country,rewaya,description&order=name_ar.asc`;
 if(q){const ar=normalizeArabic(q);resource+=`&or=(search_name_ar.ilike.*${encodeURIComponent(ar)}*,search_name_en.ilike.*${encodeURIComponent(q.toLowerCase())}*)`;}
 const res=await db('app',resource,{headers:{range:`${from}-${to}`}},true);return json({data:res.data,page,limit,total:res.count??0,next_page:res.count!=null&&to+1<res.count?page+1:null},200,{'cache-control':cache('medium')});}
async function reciter(id:string){assertUuid(id);const rows=(await db('app',`reciters?id=eq.${id}&deleted_at=is.null&is_active=eq.true&select=id,slug,name_ar,name_en,image_url,country,rewaya,description`)).data as any[];if(!rows[0])throw new ApiError(404,'NOT_FOUND','Reciter not found');return json({data:rows[0]},200,{'cache-control':cache('medium')});}
async function reciterSurahs(id:string){assertUuid(id);const tracks=(await db('app',`reciter_tracks?reciter_id=eq.${id}&is_active=eq.true&select=id,surah_id,media_id,audio_url,duration_ms,quality,rewaya,format,bitrate_kbps&order=surah_id.asc`)).data as any[];const surahs=(await db('app','surahs?select=id,number,name_ar,name_en,ayah_count&order=number.asc')).data as any[];const map=new Map(tracks.map(t=>[t.surah_id,t]));const out=[] as any[];for(const s of surahs){const t=map.get(s.id);if(!t)continue;let playback_url=t.audio_url??null;if(t.media_id&&!playback_url){const variants=(await db('app',`processed_media_variants?media_id=eq.${t.media_id}&status=eq.AVAILABLE&select=bucket_id,object_key&order=created_at.desc&limit=1`)).data as any[];if(variants[0])playback_url=await createSignedDownload(variants[0].bucket_id,variants[0].object_key,900);}out.push({surah:s,track:{id:t.id,media_id:t.media_id,duration_ms:t.duration_ms,quality:t.quality,rewaya:t.rewaya,format:t.format,bitrate_kbps:t.bitrate_kbps,playback_url}});}return json({data:out},200,{'cache-control':cache('short')});}
async function surahs(){const data=(await db('app','surahs?select=id,number,name_ar,name_en,ayah_count&order=number.asc')).data as any[];if(data.length!==114)throw new ApiError(503,'CATALOG_INTEGRITY','Surah catalog is incomplete');return json({data},200,{'cache-control':cache('long')});}
async function appConfig(){const rows=(await db('app','app_config?is_public=eq.true&select=key,value&order=key.asc')).data as any[];const data=Object.fromEntries(rows.map(r=>[r.key,r.value]));return json({data},200,{'cache-control':cache('medium')});}
async function featured(){const cfg=(await db('app','app_config?key=eq.featured_station&is_public=eq.true&select=value')).data as any[];const id=cfg[0]?.value;if(!id)return json({data:[]},200,{'cache-control':cache('medium')});const rows=(await db('app',`stations?id=eq.${encodeURIComponent(String(id))}&deleted_at=is.null&select=id,slug,name_ar,name_en,logo_url,station_source,stream_type,stream_url,is_active,production_enabled,rights_status,commercial_use_status,deleted_at`)).data as any[];const e=env();const data=rows.filter(r=>publicInternalEligible(r,e.environment)||publicExternalEligible(r)).map(r=>({type:'STATION',id:r.id,slug:r.slug,name_ar:r.name_ar,name_en:r.name_en,logo_url:r.logo_url,playback_url:stationStream(r)}));return json({data},200,{'cache-control':cache('medium')});}
async function search(request:Request){await rateLimit(`search:${ip(request)}`,60,60_000);const url=new URL(request.url);const raw=assertString(url.searchParams.get('q'),'q',120)!;if(raw.length<2)throw new ApiError(422,'VALIDATION_ERROR','q must contain at least 2 characters');const q=safeLike(raw),ar=normalizeArabic(raw);const [stations,rs,ss]=await Promise.all([db('app',`stations?deleted_at=is.null&is_active=eq.true&or=(search_name_ar.ilike.*${encodeURIComponent(ar)}*,search_name_en.ilike.*${encodeURIComponent(q.toLowerCase())}*)&select=id,slug,name_ar,name_en,station_source,stream_type,stream_url,production_enabled,rights_status,commercial_use_status,deleted_at&limit=10`),db('app',`reciters?deleted_at=is.null&is_active=eq.true&or=(search_name_ar.ilike.*${encodeURIComponent(ar)}*,search_name_en.ilike.*${encodeURIComponent(q.toLowerCase())}*)&select=id,slug,name_ar,name_en,image_url,rewaya&limit=10`),db('app',`surahs?or=(name_ar.ilike.*${encodeURIComponent(q)}*,name_en.ilike.*${encodeURIComponent(q)}*)&select=id,number,name_ar,name_en,ayah_count&limit=10`)]);const e=env();return json({data:{stations:(stations.data as any[]).filter(r=>publicInternalEligible(r,e.environment)||publicExternalEligible(r)).map(r=>({...r,stream_url:undefined,playback_url:stationStream(r)})),reciters:rs.data,surahs:ss.data}},200,{'cache-control':cache('short')});}

export async function dispatchPublic(request:Request,parts:string[]):Promise<{response:Response}|null>{
  if(parts[0]==='stations'&&request.method==='GET'){if(parts.length===1)return{response:await publicStations(request)};if(parts.length===2)return{response:await publicStation(parts[1])};if(parts.length===3&&parts[2]==='now-playing')return{response:await nowPlaying(parts[1])};}
  if(parts[0]==='categories'&&request.method==='GET')return{response:await categories()};if(parts[0]==='reciters'&&request.method==='GET'){if(parts.length===1)return{response:await reciters(request)};if(parts.length===2)return{response:await reciter(parts[1])};if(parts.length===3&&parts[2]==='surahs')return{response:await reciterSurahs(parts[1])};}
  if(parts[0]==='surahs'&&request.method==='GET')return{response:await surahs()};if(parts[0]==='featured'&&request.method==='GET')return{response:await featured()};if(parts[0]==='app-config'&&request.method==='GET')return{response:await appConfig()};if(parts[0]==='search'&&request.method==='GET')return{response:await search(request)};
  return null;
}
