import { ApiError, redact } from './contracts';
import type { AdminContext } from './auth';
import { sessionCookies } from './auth';
export function requestId(request:Request){const supplied=request.headers.get('x-request-id');return supplied&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(supplied)?supplied:crypto.randomUUID();}
export function json(data:unknown,status=200,headers?:HeadersInit){const h=new Headers(headers);h.set('content-type','application/json; charset=utf-8');return new Response(JSON.stringify(data),{status,headers:h});}
export function fail(error:unknown,id:string){const e=error instanceof ApiError?error:new ApiError(500,'INTERNAL_ERROR','Unexpected server error');if(!(error instanceof ApiError))console.error(JSON.stringify({level:'ERROR',event:'API_ERROR',request_id:id,error:redact({message:error instanceof Error?error.message:String(error)})}));return json({error:{code:e.code,message:e.message,request_id:id}},e.status,{'x-request-id':id,'cache-control':'no-store'});}
export function attachContext(response:Response,id:string,ctx?:AdminContext){response.headers.set('x-request-id',id);if(ctx?.refreshed){for(const c of sessionCookies({access_token:ctx.refreshed.access,refresh_token:ctx.refreshed.refresh,expires_in:ctx.refreshed.expires}))response.headers.append('set-cookie',c);}return response;}
export async function body(request:Request,maxBytes=64_000){const length=Number(request.headers.get('content-length')??0);if(length>maxBytes)throw new ApiError(413,'PAYLOAD_TOO_LARGE','Request body is too large');try{return await request.json()}catch{throw new ApiError(400,'MALFORMED_JSON','Malformed JSON body');}}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(!origin)return;const u=new URL(request.url);if(new URL(origin).host!==u.host)throw new ApiError(403,'CSRF_REJECTED','Cross-origin mutation rejected');}
